package moderate;

public class EvenFibonacciSum {
	
	
	//Write a method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n.
	//Each new element in the Fibonacci sequence is generated by adding the previous two elements.
	//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	
	public static Integer evenFibonacciSum(Integer n) {
		int first = 1;
		int sec = 2;
		int solution = 0;
		
		for(;sec <= n;) {
			if(sec%2 == 0 && sec <= n ) {
				solution = solution + sec;
			}
			int newelement = first + sec;
			first = sec;
			sec = newelement;

		}
		
		return solution;
	}
	
	
	public static void main(String[]args) {
		System.out.println(evenFibonacciSum(50));
	}
	
}
